export default [
    {
        id: "Restaurant",
        icon: "",
        c_name: "餐馆",
        e_name: "Restaurant",
        children: [{
            id: "Restaurant1",
            icon: "",
            c_name: "餐馆",
            e_name: "Restaurant",
            url: "company.html"
        }, {
            id: "Staff",
            icon: "",
            c_name: "员工管理",
            e_name: "Staff",
            url: "staff.html"
        }, {
            id: "Table",
            icon: "",
            c_name: "桌子",
            e_name: "Table",
            url: "tables.html"
        }, {
            id: "Delivery",
            icon: "",
            c_name: "外送区域",
            e_name: "Delivery Area",
            url: "deliveryArea.html"
        }, {
            id: "Gallery",
            icon: "",
            c_name: "图片库",
            e_name: "Gallery",
            url: "gallery.html"
        }, {
            id: "Analysis",
            icon: "",
            c_name: "分析",
            e_name: "Analysis",
            url: "report.html"
        }]
    }, {
        id: "Menu",
        icon: "",
        c_name: "菜单",
        e_name: "Menu",
        children: [{
            id: "Menu1",
            icon: "",
            c_name: "菜单编辑",
            e_name: "Menu",
            url: "menu/index.html"
        }, {
            id: "Modifier",
            icon: "",
            c_name: "调味指示",
            e_name: "Modifier Actions",
            url: "globalOptions.html"
        }, {
            id: "Item",
            icon: "",
            c_name: "菜品单位",
            e_name: "Item Size",
            url: "itemSize.html"
        }, {
            id: "Course",
            icon: "",
            c_name: "菜序名",
            e_name: "Course Name",
            url: "course.html"
        }, {
            id: "Promotion",
            icon: "",
            c_name: "促销策略",
            e_name: "Promotion",
            url: "promotionStrategy.html"
        }, {
            id: "TimeBase",
            icon: "",
            c_name: "按时计费",
            e_name: "TimeBase Fee",
            url: "hourlyRate.html"
        }, {
            id: "Order",
            icon: "",
            c_name: "订单类型",
            e_name: "Order Type",
            url: "orderTypeSetting.html"
        }]
    }, {
        id: "Inventory",
        icon: "",
        c_name: "库存管理",
        e_name: "Inventory",
        children: [{
            id: "Items",
            icon: "",
            c_name: "物品",
            e_name: "Items",
            url: "inventoryItem.html"
        }, {
            id: "Channel",
            icon: "",
            c_name: "渠道",
            e_name: "Channel",
            url: "inventoryInfo.html"
        }, {
            id: "Management",
            icon: "",
            c_name: "管理",
            e_name: "Management",
            url: "inventoryManagement.html"
        }]
    }, {
        id: "PriceAndPayment",
        icon: "",
        c_name: "价格与付款",
        e_name: "PriceAndPayment",
        children: [{
            id: "Tax",
            icon: "",
            c_name: "祱",
            e_name: "Tax",
            url: "tax.html"
        }, {
            id: "Discount",
            icon: "",
            c_name: "折扣",
            e_name: "Discount",
            url: "discount.html"
        }, {
            id: "Charge",
            icon: "",
            c_name: "加收",
            e_name: "Charge",
            url: "charge.html"
        }, {
            id: "Payment",
            icon: "",
            c_name: "付款类型",
            e_name: "Payment Type",
            url: "paymentAccount.html"
        }, {
            id: "Cash",
            icon: "",
            c_name: "收银机",
            e_name: "Cash Register",
            url: "cashRegisterActivity.html"
        }]
    }, {
        id: "System",
        icon: "",
        c_name: "系统设置",
        e_name: "System1",
        children: [{
            id: "Setting",
            icon: "",
            c_name: "系统",
            e_name: "Setting",
            url: "settings.html"
        }, {
            id: "Printer",
            icon: "",
            c_name: "打印机和设备",
            e_name: "Printer&Device",
            url: "printers.html"
        }, {
            id: "Print",
            icon: "",
            c_name: "打印设置",
            e_name: "Print-Setup",
            url: "printingSetup.html"
        }, {
            id: "Language",
            icon: "",
            c_name: "多语言",
            e_name: "Language",
            url: "language.html"
        }, {
            id: "Partner",
            icon: "",
            c_name: "整合功能应用",
            e_name: "Partner Integration",
            url: "partnerIntegration.html"
        }]
    }, {
        id: "Customer",
        icon: "",
        c_name: "顾客管理",
        e_name: "Customer",
        children: [{
            id: "Gift",
            icon: "",
            c_name: "礼品卡",
            e_name: "Gift Card",
            url: "giftCard.html"
        }, {
            id: "Loyalty",
            icon: "",
            c_name: "会员卡",
            e_name: "Loyalty",
            url: "loyaltyCard.html"
        }, {
            id: "Customer1",
            icon: "",
            c_name: "顾客信息",
            e_name: "Customer",
            url: "customer.html"
        }]
    }
]